### ISSUE TITLE
Minimal Ember version?

### ISSUE THREAD

**Issue by bekharsky** [zestia/ember-select-box#1]
Hi! I've tried to install this on 1.13.10 and had no success:

"Uncaught Error: Could not find module `ember-component` imported from `ember-cli-select-box/components/select-box/native`"

What is minimal Ember.js version supported?

**Comment by amk221** [comment]
It relies on contextual components, so [this](http://emberjs.com/blog/2015/11/16/ember-2-2-released.html#toc_contextual-components) would be the minimal version.

I will put a badge on the readme so this is more clear.
Thanks
