### ISSUE TITLE
Error in fastboot

### ISSUE THREAD

**Issue by wuron** [zestia/ember-select-box#12]
I'm getting following error in console when running app with fastboot.
```
There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot read property 'trim' of undefined
...
ember-select-box/mixins/select-box/select-box/searchable.js:13:1
```
Looks like the addon is trying to get `jQuery.trim` but jQuery is unavailable in fastboot mode.

**Comment by amk221** [comment]
I can fix that specific error, but phasing out jQuery altogether is a bit more challenging

**Comment by amk221** [comment]
I've removed use of jQuery's `trim` in 1.2.1, let me know if that helps.
(Although, I presume you'll just get warnings about other uses of jQuery?)

**Comment by wuron** [comment]
Yeah, now I'm getting warning about `contains` in `ember-select-box/mixins/select-box/general/click-outside.js:9:1`.

**Comment by wuron** [comment]
Looks like in some places it can be easily fixed, just like with trim, but in other places where addon uses event listeners, there should be a check for fastboot. Something like in `ember-simple-auth` or other addons: https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/authenticated-route-mixin.js#L38

**Comment by amk221** [comment]
Yeh, bare with me - I'll see if I can do it today

**Comment by amk221** [comment]
I've made headway [removing](https://github.com/amk221/ember-select-box/commit/ad867e25096b05f17e9666ffa4b162486f118859) [reliance](https://github.com/amk221/ember-select-box/commit/1b4c794475ba6d75960e1b6e0f437467daf6f09c) on jQuery, but come across a blocker for now
https://github.com/emberjs/ember.js/issues/15578
