### ISSUE TITLE
Input component should extend Ember's TextField

### ISSUE THREAD

**Issue by markcellus** [zestia/ember-select-box#13]
Would it be acceptable to have [select-box/input.js](https://github.com/amk221/ember-select-box/blob/master/addon/components/select-box/input.js) extend [Ember's TextField](https://www.emberjs.com/api/ember/2.14.1/classes/Ember.TextField) class to have it behave like the `{{input}}` helper and pass all properties that the `{{input}}` helper allows?

**Comment by amk221** [comment]
Thanks
https://github.com/amk221/ember-select-box/commit/a5d62137cbc928d37bb4bdd2cd820bcea0483f49

**Comment by markcellus** [comment]
Awesome! Thanks

**Comment by amk221** [comment]
Doing this accidentally made input two-way bound, I didn't want that behaviour.

The [test](https://github.com/amk221/ember-select-box/blob/a9d6072b5fa4761b951247bd88d186e17a5adc4f/tests/integration/components/input-test.js#L156) I had to prevent this had a mistake (see the call to `trigger`) which meant I didn't catch it.

I'm going to have to make the input component _not_ extend Ember's TextField, but I will keep the same attribute bindings.

**Comment by markcellus** [comment]
I see. Yeah I never understood exactly why Ember's input helper is two-way bound by default. Seems like it makes more sense to pass it actions to respond to value changes.

**Comment by markcellus** [comment]
Just curious though, can't you just use `Ember.computed.oneWay` to force one-way binding?

**Comment by amk221** [comment]
Don't think so, one way cp can't bind `value` to itself?
[have a play](https://ember-twiddle.com/557ca159e8e9ed22c426d335b468b03e?openFiles=components.my-input1.js%2C) if you like :)

**Comment by markcellus** [comment]
Yup, definitely. I believe it's commonly understood that the input helper's `value` property is two-way binded by default. So to force it to use one-way binding, I think people know to do `{{input value=(readonly myValue)}}` based on the documentation.

In your twiddle example, if one-way is desired, instead of doing:

```hbs
{{my-input1 value=myObj.value1}}
```

you would do

```hbs
{{my-input1 value=(readonly myObj.value1)}}
```

I hear Ember is going to eventually change this in future versions so that the `{{input}}` helper's `value` is not two-way bound by default and you will explicitly have to declare it to be using the `{{mut}}` helper.

**Comment by amk221** [comment]
Ah yes of course, how would you like to proceed? ;)

**Comment by markcellus** [comment]
Oh, I was just informing you. Using a custom `<input>` component element is fine--all attributes you've bounded cover my use-case. But you'll just have to keep adding `attributeBindings` as new input attributes are added to the HTML spec (and any custom ones that may be added by Ember in the future). But if you're fine with doing that, it's cool with me too. ;)

**Comment by amk221** [comment]
yeh, fine with that. ty
