### ISSUE TITLE
Exposing mixins?

### ISSUE THREAD

**Issue by markcellus** [zestia/ember-select-box#16]
Hey @amk221. you guys mind exposing the mixins inside of the `app` folder to the consumer? It's preventing me from upgrading since there was quite a bit of code relying on those.

**Comment by markcellus** [comment]
Ah nevermind, looks like you still are exposing... they were just moved to new locations. I can update. Closing...

**Comment by amk221** [comment]
Ah no problem!

I'd like to know your use cases. I'm trying to nudge users towards not using them.

P.S. Sorry for the churn!
