### ISSUE TITLE
Add `name` to `attributeBindings` of `select-box/native`

### ISSUE THREAD

**Issue by krasnoukhov** [zestia/ember-select-box#4]
I'm not sure why `name` is not on that list since that's something that `<select>` allows. For me, it would be useful so I can use Capybara's `select` method with `from` option: http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Actions#select-instance_method

I could open a PR if that change is ok with you. Thanks!

**Comment by amk221** [comment]
Ah, silly me!
Sure thing if you'd like to make a PR that's fine with me :)

**Comment by amk221** [comment]
Thank you!

**Comment by krasnoukhov** [comment]
No, thank you! :shipit:
