### ISSUE TITLE
Added performance test is a bit sketchy

### ISSUE THREAD

**Issue by derrabauke** [zestia/ember-select-box#63]
Hey folks! Thanks for the cool addon and the latest refactoring! :clap: 

One minor thing came to my mind when I had a look at the currently failig CI:

I think the added [`performance` test](https://github.com/zestia/ember-select-box/blob/da79196b409d034d488f16c35bdf5bd04a9f937a/tests/acceptance/performance-test.js) is not very meaningful, since you are also testing "*how fast can we produce 10.000 array entries*". Shouldn't we measure only the time when *render-begin* to *render-end*?

Further why add a minimum time for that test?

Cheers

**Comment by amk221** [comment]
It's true it could be better, it's very approximate, but it does the job in catching this issue https://github.com/tracked-tools/tracked-built-ins/issues/405, which was all I really wanted.

**Comment by derrabauke** [comment]
Alright, thanks for the clarification. :+1:
