### ISSUE TITLE
Support HTML `title` Attribute

### ISSUE THREAD

**Issue by nadnoslen** [zestia/ember-select-box#8]
I just tried to set the `title` attribute of one of my `select-box.native` components and the title attribute is not appearing in the markup.  Can we add that to the component's `attributeBindings` array?
### Workaround (in your `app/app.js`)

```
import EmberSelectBoxNative from 'ember-select-box/components/select-box/native';

// technique from http://stackoverflow.com/a/20293724/545137
EmberSelectBoxNative.reopen({
  attributeBindings: ['title']
});
```

**Comment by nadnoslen** [comment]
I can try to find time to fork, fix, test, & PR.

**Comment by amk221** [comment]
Thanks.
Currently on holiday, will sort next week
